### PR TITLE
adding part splits

### PR DESCRIPTION
**Pull request by entorb**
As discussed in #34, here the introduction of part splits. 
The font for the part title pages does not fit to the rest of the book, could someone with more LaTeX font experience please take care for this?

### CODE REVIEW

**Comment by rrthomas** [comment]
I think I've dealt with this now; please check!

**Comment by entorb** [comment]
Code looks good, but since I am currently not home, I can’t compile it to PDF and check the output. I suggest merging it, since you are the LaTeX expert ;-)

**Comment by entorb** [comment]
Thanks!
Could you please trigger the building as well?

**Comment by rrthomas** [comment]
Done.

**Pull request merged**
