### PR TITLE
letters and written in handwritten font

### PR DESCRIPTION
**Pull request by yeKcim**
like parsel specific font, a specific font for letters and handwritten text. Use a font already used (architechdaughter.ttf)

### CODE REVIEW

**Comment by rrthomas** [comment]
I like the idea of a specific font. I appreciate you reusing a font already used, but I think that McGonagall would have unusually old-fashioned handwriting, and something like Pecita would be better for other characters' handwritten letters and notes. What do you think?

**Comment by yeKcim** [comment]
Not a big fan of Pecita, [sage-sans](https://www.dafont.com/fr/sage-sans.font) or [vavont](https://www.dafont.com/fr/vavont.font) could be easiest to read. [Graphe Alpha](https://www.dafont.com/fr/graphe.font) is great too but I would have to add accents.

In an ideal version, each character should have his own writing

**Comment by rrthomas** [comment]
> Not a big fan of Pecita,

Fair enough!

> [sage-sans](https://www.dafont.com/fr/sage-sans.font)

Clear if a bit impersonal.

> or [vavont](https://www.dafont.com/fr/vavont.font)

Details like circles instead of dots over "i" and "j" make it a bit too individualistic to use for all characters.

>[Graphe Alpha](https://www.dafont.com/fr/graphe.font) is great too but I would have to add accents.

I like it!

> In an ideal version, each character should have his own writing

This occurred to me too, but of course I wouldn't demand it in a PR like this one. If you felt like doing it, then most or all of the fonts we've discussed so far could be candidates.

**Comment by yeKcim** [comment]
I’ve tried with a modified Graphe Alpha font (I’ve sent a mail to the author, no answer yet…).

graphe preview

Not perfect but not bad

**Comment by rrthomas** [comment]
Yes, I like this! Thanks very much for working on this sort of general improvement as well as on your translation; it is really lifting the experience of reading HPMOR in all languages!

**Comment by yeKcim** [comment]
Problem is… my git skill is limited (I learn but it's not easy). My english branch on my fork use this font but I don’t know how to add this modification in this pull request instead of a new one 😅

**Comment by rrthomas** [comment]
> Problem is… my git skill is limited (I learn but it's not easy). My english branch on my fork use this font but I don’t know how to add this modification in this pull request instead of a new one sweat_smile

It looks like you worked it out?

**Comment by yeKcim** [comment]
Yes.

Git is powerful but it still not understand that you need a git pull if you don’t type it… I'm better with git than I thought, I'm just worse with the whole computer than I thought.

**Comment by rrthomas** [comment]
Please could you squash the two commits in this PR into a single commit?

**Comment by rrthomas** [comment]
Two small things:

1. Are you checking in the `.sfd` source file because of your added accents? If so, I think it would be better to put it in another GitHub project where people can find it by searching (and of course try to push your changes upstream).
2. Could you define a macro for the name of the font rather than repeat the name? If (later?) we get to the stage of one font per character, then we'll want an argument to the `letter` and `written` environments.

**Comment by yeKcim** [comment]
1. we probably can delete .sfd file
2. added in my todolist

**Comment by rrthomas** [comment]
> 1. we probably can delete .sfd file

Cool, please do that. (But it will be available somewhere for translators? Please add a link to the docs!)
 
>     2. added in my todolist

Great, I will wait for that.

**Comment by yeKcim** [comment]
I surrender

**Comment by yeKcim** [comment]
😑 that's the fonts I’ve tried. I didn’t wanted to add them. Mistake, sorry.

**Comment by rrthomas** [comment]
This is looking good except for the gitology: you've merged the master branch into your branch (and your branch should now be merged back into the master branch). I think you meant to rebase your branch on master. But don't worry: I like the changes, and I'll work out how to apply them.

**Comment by yeKcim** [comment]
I was proud of my squash, everything was right until push. I don't really understand what I've done wrong but I'm done with it. Thank you for giving me instructions at the limit of git comprehension, I progress! (still not understand what I'm doing sometimes but better than before)

**Comment by rrthomas** [comment]
I've fixed up git. It was easy: I just ran `git rebase master` on your branch, which removed the merge commit, since there was no other difference from `master` than your changes in the single commit you made.

Just to be sure, please can you check that the PR now looks good to you?

**Comment by yeKcim** [comment]
seems to be ok

**Pull request merged**
