### PR TITLE
Add hyphen to Parsel font

### PR DESCRIPTION
**Pull request by yeKcim**
two extracts of dialogues are in emph whereas parsel would seem to be more appropriate to me (as I understand the text at least). My English is rather limited, maybe it's just a misinterpretation

### CODE REVIEW

**Comment by yeKcim** [comment]
If you prefer 2 different PR, tell me.

**Comment by rrthomas** [comment]
Thanks very much for this. I fixed the `\parsel` uses with my own commit; it was also necessary to remove the double "s", as that is added automatically by `\parsel`.

Please could you therefore remove that commit from this PR, and I'll then merge the PR just to fix the font? (Thanks for the fix to the font too!)

**Comment by rrthomas** [comment]
OK, now please squash into a single commit (the edits to the LaTeX sources should cancel out and disappear altogether—magic!).

**Comment by rrthomas** [comment]
Same problem as last time! You have a merge commit from master to your PR branch. You should be able to fix it by rebasing your branch on my master:

```
$ git rebase origin/master
```

**Comment by yeKcim** [comment]
Everytime I've got this same problem, I really have to understand where is my mistake! 😁

**Comment by rrthomas** [comment]
Yes, I think it's worth learning what is going wrong here!

**Comment by yeKcim** [comment]
my kid REALLY annoying me to have acces to my computer NOW, I’ll try later to understand, it will take me MORE time than his hour daily screen time 😁

**Comment by rrthomas** [comment]
Oops, what happened? I haven't applied this PR!

**Comment by yeKcim** [comment]
I'm working on it, just want to work from scratch. I'd got too much errors I can't understant on this PR, so I try to create a new branch and will PR again

**Comment by yeKcim** [comment]
```sh
git checkout -b myenglishhpmor 1ed44885c8e1e84f0128484a3000780564ce34e5
git push
git push --set-upstream origin myenglishhpmor
git remote add upstream https://github.com/rj20/hpmor.git
git rebase origin/master
```
It will be harder to understand than I though. My problem is that I want to create a branch "english" in my fork, that follow your repo (my master branch is 200 comits different). I want to apply few changes on this english branch to PR just few little comits. I understand git for personnal use but fork and PR logic is really hard to understand for me.

Updated Parseltongue font is in my master repo. I will find a way to give it to you. By the way I want to release my 22.03 release of french hpmor and I’ve got to work on epub scripts (did you know there is translations in these scripts, that’s not really good reusable scripts…). See you soon. Sorry for the noise.

**Comment by rrthomas** [comment]
It might be easier for you to have two forks: one for your translation, and one for PRs to upstream.

I know that the ePUB scripts have those issues. You will see they were only added quite recently (in fact, by the author of a German translation.) If you have any improvements in that area, that would be great (even if it's just instructions for translators to look at them). I thought at the time that it was better to have ePUBs (a major issue) than to wait until they scripts could be internationalised, or made language-independent.

**Pull request closed without merging**
